services:
  postgres:
    image: postgres:17
    container_name: sebrae-db
    environment:
      POSTGRES_DB: sebrae
      POSTGRES_USER: ${DB_USERNAME:-polaris}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sebrae-data:/var/lib/postgresql/data

volumes:
  sebrae-data: