package io.polaris.sebrae.model.enums;

public enum EventType {
	VIDEO_PAUSED,
	VIDEO_RESUMED,
	VIDEO_ACCELERATED,
	VIDEO_REWOUND,
	LESSON_STARTED,
	LESSON_COMPLETED,
	LESSON_REVISITED,
	PAGE_OPENED,
	PAGE_COMPLETED,
	READING_TIME,
	EXTERNAL_LINK_CLICKED,
	CONTENT_COPIED,
	MATERIAL_DOWNLOADED,
	CONTENT_EXPANDED,
	QUIZ_ANSWERED,
	SCREEN_INACTIVE,
	SESSION_ENDED,
	COURSE_ABANDONED
}
